# Use the official .NET SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy the project files
COPY {ToDoApp.Data}/*.csproj ./{ToDoApp.Data}/
RUN dotnet restore {ToDoApp.Data}/{ToDoApp.Data}.csproj

# Copy the project files
COPY {ToDoApp.Api}/*.csproj ./{ToDoApp.Api}/
RUN dotnet restore {ToDoApp.Api}/{ToDoApp.Api}.csproj

# Copy the rest of the application code
COPY {ToDoApp.Service}/. ./{ToDoApp.Service}/
RUN dotnet publish {ToDoApp.Service}/{ToDoApp.Service}.csproj -c Release -o out

# Use the official ASP.NET Core runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .

# Specify the command to run the app
ENTRYPOINT ["dotnet", "{ToDoApp.Api}.dll"]